name: Prover Bench on halo2 PR
on:
  pull_request:
    types: [opened, reopened]

jobs:
  Prover-benches-via-repo-dispatch-from-halo2-fork:
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ github.actor }}
      TOKEN: ${{ secrets.PAT2 }}
    steps:
      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install curl
      - name: echo user
        run: echo "${{ env.GH_USER }}"
      - name: echo secret
        run: echo "${{ env.TOKEN }}"
      - name: Send repo api call
        run: |
          curl \
           -X POST \
           -H "Accept: application/vnd.github.v3+json" \
           -u ${{ env.GH_USER }}:${{ env.TOKEN }} \
           https://api.github.com/repos/AronisAt79/Test1/actions/workflows/test.yml/dispatches \
           -d '{"ref":"main"}'
      
