name: Create Comment

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    
jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body: |
            This is a drill
          
          reactions: '+1'
