name: Prover Bench on halo2 PR
on:
  pull_request:
    types: [opened, reopened]

jobs:
  Send-a-repo-dispatch-signal-to-circuits  
    runs-on: ubuntu-latest
    steps:
    - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install curl -y
    - name: send repo api call   
        run: curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/AronisAt79/Test1/languages
        shell: bash

#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
