name: Prover Bench on halo2 PR
on:
  pull_request:
    types: [opened, reopened]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
