name: Update PR Reviewers

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  update_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/AronisAt79/Test2/pulls/9/requested_reviewers -d '{"reviewers":["AronisAt79"]}'
